// ZXTune formats, curated for the site.
//
// Checked against the engine itself: `plugins` are the ids its plugin list
// reports (js/plugins-data.js, generated from zxtune.plugins()), names follow
// the engine's own descriptions, and chips follow the device each plugin
// declares. "ID|text" picks, among plugins sharing an id, those whose
// description contains the text. Extensions are the ones the files in the repository's samples/
// carry, or the usual ones for the well-known formats; ZXTune itself goes by
// content, not by name. No years or authors unless they could be backed.
window.ZXTUNE_FORMATS = [
  // AY / YM
  {id:"pt3", ext:".pt3", name:"Pro Tracker v3.x", aka:"PT3", cat:"aym", chip:"AY-3-8910 / YM2149", platform:"ZX Spectrum", exts:[".pt3"], plugins:["PT3","COMPILEDPTU13"],
   desc:"ZX Spectrum の AY 向けトラッカー Pro Tracker 3.x のモジュール。",
   long:"PC 用の Vortex Tracker II (Sergey Bulba) も PT3 を読み書きできます。2つの PT3 を連結した TurboSound (AY×2) の曲も PT3 プラグインが扱い、ProTracker Utility v1.3 でプレイヤーごとコンパイルされた曲は、中の楽曲データを取り出して再生します。",
   features:["AY 3ch","TurboSound 対応","コンパイル済みも展開"]},
  {id:"pt2", ext:".pt2", name:"Pro Tracker v2.x", aka:"PT2", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".pt2"], plugins:["PT2","COMPILEDPT24"],
   desc:"Pro Tracker 2.x のモジュール。",
   long:"Pro Tracker v2.40 (Phantom Family) のプレイヤーごとコンパイルされた曲も、中の楽曲データを取り出して再生します。",
   features:["AY 3ch","コンパイル済みも展開"]},
  {id:"pt1", ext:".pt1", name:"Pro Tracker v1.x", aka:"PT1", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".pt1"], plugins:["PT1"],
   desc:"Pro Tracker 1.x のモジュール。",
   long:"ZXTune の PT1 プラグインで再生します。",
   features:["AY 3ch"]},
  {id:"stc", ext:".stc", name:"Sound Tracker v1.x (コンパイル済み)", aka:"STC", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".stc"], plugins:["STC"],
   desc:"Sound Tracker 1.x の曲を、再生用にコンパイルした形式。",
   long:"コンパイル前のモジュールは ST1、Sound Tracker Pro の曲は STP として別のプラグインが扱います。",
   features:["AY 3ch"]},
  {id:"st1", ext:".st1", name:"Sound Tracker v1.x", aka:"ST1", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".st1",".s"], plugins:["ST1"],
   desc:"コンパイル前の Sound Tracker 1.x モジュール。",
   long:"コンパイル済みの曲 (STC) とは別のプラグインで再生します。",
   features:["AY 3ch"]},
  {id:"stp", ext:".stp", name:"Sound Tracker Pro (コンパイル済み)", aka:"STP", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".stp"], plugins:["STP|Sound Tracker Pro Compiled","COMPILEDSTP1","COMPILEDSTP2"],
   desc:"Sound Tracker Pro でコンパイルした曲。",
   long:"Sound Tracker Pro v1.x / v2.x のプレイヤーごと保存された曲も、中の楽曲データを取り出して再生します。",
   features:["AY 3ch","コンパイル済みも展開"]},
  {id:"st3", ext:".st3", name:"Sound Tracker v3.x (コンパイル済み)", aka:"ST3", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".st3"], plugins:["ST3","COMPILEDST3"],
   desc:"Sound Tracker 3.x でコンパイルした曲。",
   long:"Sound Tracker v3.x のプレイヤーごと保存された曲も、中の楽曲データを取り出して再生します。",
   features:["AY 3ch","コンパイル済みも展開"]},
  {id:"asc", ext:".asc", name:"ASC Sound Master", aka:"ASC", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".asc",".as0"], plugins:["ASC","AS0","COMPILEDASC0","COMPILEDASC1","COMPILEDASC2"],
   desc:"ASC Sound Master の v1.x と v0.x (.as0) のモジュール。",
   long:"ASC Sound Master v0.x / v1.x / v2.x のプレイヤーごとコンパイルされた曲も、中の楽曲データを取り出して再生します。",
   features:["AY 3ch","コンパイル済みも展開"]},
  {id:"sqt", ext:".sqt", name:"SQ-Tracker (コンパイル済み)", aka:"SQT", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".sqt"], plugins:["SQT"],
   desc:"SQ-Tracker でコンパイルした曲。",
   long:"デジタル版の SQ Digital Tracker (SQD) とは別の形式です。",
   features:["AY 3ch"]},
  {id:"psc", ext:".psc", name:"Pro Sound Creator v1.xx", aka:"PSC", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".psc"], plugins:["PSC"],
   desc:"Pro Sound Creator 1.xx のモジュール。",
   long:"ZXTune の PSC プラグインで再生します。",
   features:["AY 3ch"]},
  {id:"psm", ext:".psm", name:"Pro Sound Maker", aka:"PSM", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".psm"], plugins:["PSM|Pro Sound Maker"],
   desc:"Pro Sound Maker のモジュール。",
   long:"同じ .psm でも、PC の Epic MegaGames MASI は別のプラグイン (モジュール系) が扱います。",
   features:["AY 3ch"]},
  {id:"ftc", ext:".ftc", name:"Fast Tracker v1.x", aka:"FTC", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".ftc"], plugins:["FTC"],
   desc:"ZX Spectrum の AY 向けトラッカー Fast Tracker 1.x のモジュール。",
   long:"PC の FastTracker 2 (XM) とは別のトラッカーです。",
   features:["AY 3ch"]},
  {id:"gtr", ext:".gtr", name:"Global Tracker v1.x", aka:"GTR", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum", exts:[".gtr"], plugins:["GTR"],
   desc:"Global Tracker 1.x のモジュール。",
   long:"ZXTune の GTR プラグインで再生します。",
   features:["AY 3ch"]},
  {id:"txt", ext:".txt", name:"Vortex Tracker II (テキスト)", aka:"TXT", cat:"aym", chip:"AY-3-8910", platform:"PC (Vortex Tracker II)", exts:[".txt"], plugins:["TXT"],
   desc:"Vortex Tracker II (Sergey Bulba) がテキストで書き出すモジュール。",
   long:"エンジンには VortexTracker II という名前で登録されています。",
   features:["AY 3ch","テキスト形式"]},
  {id:"psg", ext:".psg", name:"PSG (レジスタダンプ)", aka:"PSG", cat:"aym", chip:"AY-3-8910", platform:"ZX Spectrum など", exts:[".psg"], plugins:["PSG"],
   desc:"AY/YM のレジスタへの書き込みをフレームごとに記録したダンプ。",
   long:"曲の構造ではなく、チップへの出力をそのまま再生します。",
   features:["レジスタダンプ"]},
  {id:"ym", ext:".ym", name:"YM (ST-Sound)", aka:"YM", cat:"aym", chip:"YM2149 / AY-3-8910", platform:"Atari ST など", exts:[".ym"], plugins:["YM"],
   desc:"Arnaud Carré (Leonard) の ST-Sound プロジェクトによるレジスタダンプ。",
   long:"圧縮された YM ファイルもそのまま再生します。YM ファイル自体はチップ種別を持たないため、既定では AY として鳴ります (プレイヤーの設定で YM2149F に切り替えられます)。",
   features:["レジスタダンプ","圧縮版も可"]},
  {id:"vtx", ext:".vtx", name:"VTX (Vortex Project)", aka:"VTX", cat:"aym", chip:"AY-3-8910 / YM2149", platform:"ZX Spectrum など", exts:[".vtx"], plugins:["VTX"],
   desc:"AY/YM のレジスタダンプを圧縮して収めた形式。",
   long:"チップ種別 (AY / YM) とステレオ配置をファイル内に持ち、ZXTune はその指定どおりに鳴らします (プレイヤー側の設定より優先)。",
   features:["レジスタダンプ","チップ種別を保持"]},
  {id:"ayc", ext:".ayc", name:"CPC AYC", aka:"AYC", cat:"aym", chip:"AY-3-8910", platform:"Amstrad CPC", exts:[".ayc"], plugins:["AYC"],
   desc:"Amstrad CPC の AY 音楽を収めた AYC 形式。",
   long:"ZXTune の AYC プラグインで再生します。",
   features:["AY 3ch"]},
  {id:"turbosound", ext:".ts", name:"TurboSound", aka:"TS", cat:"aym", chip:"AY-3-8910 ×2", platform:"ZX Spectrum (TurboSound 拡張)", exts:[".ts",".pt3"], plugins:["TS","PT3"],
   desc:"AY を2基載せる ZX Spectrum の拡張 TurboSound 用の6チャンネル曲。",
   long:"2つのモジュールを連結した形で保存されていて、ZXTune は2チップ分をまとめて再生します。",
   features:["AY×2 (6ch)"]},
  {id:"ay", ext:".ay", name:"AY / EMUL", aka:"AY", cat:"aym", chip:"AY-3-8910 + Z80 (+ ビーパー)", platform:"ZX Spectrum など", exts:[".ay"], plugins:["AY"],
   desc:"再生用の Z80 コードごと曲を収めた形式。ZXTune は Z80 をエミュレートして鳴らします。",
   long:"1つのファイルに複数の曲が入っている場合は、1曲ずつプレイリストに展開されます。ZX の 1bit 出力 (ビーパー) も鳴らします。",
   features:["Z80 エミュレーション","複数曲を展開"]},

  // Digital: ZX sample trackers, Amiga, soft synths
  {id:"dst", ext:".dst", name:"Digital Studio", aka:"DST", cat:"digital", chip:"DAC (Covox / SD)", platform:"ZX Spectrum", exts:[".dst"], plugins:["DST"],
   desc:"ZX Spectrum のサンプル (デジタル) トラッカー Digital Studio のモジュール。",
   long:"ZXTune は曲の情報に Digital Studio (Covox/SD) と表示します。",
   features:["サンプル再生"]},
  {id:"dmm", ext:".dmm", name:"Digital Music Maker v1.x", aka:"DMM", cat:"digital", chip:"DAC", platform:"ZX Spectrum", exts:[".dmm"], plugins:["DMM"],
   desc:"ZX Spectrum のサンプルトラッカー Digital Music Maker 1.x のモジュール。",
   long:"ZXTune の DMM プラグインで再生します。",
   features:["サンプル再生"]},
  {id:"pdt", ext:".m", name:"ProDigi Tracker v0.0x", aka:"PDT", cat:"digital", chip:"DAC", platform:"ZX Spectrum", exts:[".m"], plugins:["PDT|ProDigi"],
   desc:"ZX Spectrum のサンプルトラッカー ProDigi Tracker のモジュール。",
   long:"サンプル集では TR-DOS 流の .M という名前で置かれています。同じ PDT という ID を持つ Hudson のストリーム形式 (ゲーム音声) は別のプラグインです。",
   features:["サンプル再生"]},
  {id:"sqd", ext:".sqd", name:"SQ Digital Tracker", aka:"SQD", cat:"digital", chip:"DAC", platform:"ZX Spectrum", exts:[".sqd"], plugins:["SQD"],
   desc:"SQ Digital Tracker のモジュール。",
   long:"AY 用の SQ-Tracker (SQT) とは別の形式です。",
   features:["サンプル再生"]},
  {id:"str", ext:".str", name:"Sample Tracker v2.x", aka:"STR", cat:"digital", chip:"DAC", platform:"ZX Spectrum", exts:[".str"], plugins:["STR|Sample Tracker"],
   desc:"ZX Spectrum のサンプルトラッカー Sample Tracker 2.x のモジュール。",
   long:"ZXTune の STR プラグインで再生します。",
   features:["サンプル再生"]},
  {id:"et1", ext:".m", name:"Extreme Tracker v1.x", aka:"ET1", cat:"digital", chip:"DAC", platform:"ZX Spectrum", exts:[".m",".d"], plugins:["ET1"],
   desc:"ZX Spectrum のサンプルトラッカー Extreme Tracker 1.x のモジュール。",
   long:"サンプル集では TR-DOS 流の .M / .D という名前で置かれています。",
   features:["サンプル再生"]},
  {id:"chi", ext:".chi", name:"Chip Tracker", aka:"CHI", cat:"digital", chip:"DAC", platform:"ZX Spectrum", exts:[".chi"], plugins:["CHI"],
   desc:"ZX Spectrum のサンプルトラッカー Chip Tracker のモジュール。",
   long:"ZXTune の CHI プラグインで再生します。",
   features:["サンプル再生"]},
  {id:"ahx", ext:".ahx", name:"AHX / HivelyTracker", aka:"AHX", cat:"digital", chip:"ソフトウェア合成", platform:"Amiga", exts:[".ahx",".hvl"], plugins:["AHX|Abyss","HVL"],
   desc:"Amiga の AHX (Abyss' Highest eXperience) と、その後継 HivelyTracker のモジュール。",
   long:"同じ AHX という ID でも、CRI のゲーム音声形式 (AHX) は別のプラグインです。",
   features:["波形合成"]},
  {id:"v2m", ext:".v2m", name:"Farbrausch V2 Synthesizer System", aka:"V2M", cat:"digital", chip:"ソフトウェア合成", platform:"PC (デモシーン)", exts:[".v2m"], plugins:["V2M"],
   desc:"デモグループ Farbrausch のソフトウェアシンセ V2 の曲。",
   long:"音を合成で作るので、ファイルにサンプルをほとんど持ちません。",
   features:["波形合成"]},

  // FM / SAA
  {id:"tfc", ext:".tfc", name:"TurboFM Compiled Dump", aka:"TFC", cat:"fm", chip:"YM2203 ×2 (TurboFM)", platform:"ZX Spectrum (TurboFM 拡張)", exts:[".tfc"], plugins:["TFC"],
   desc:"TurboFM 用にコンパイルされたダンプ。",
   long:"TurboFM は YM2203 を2基使う ZX Spectrum の FM 音源拡張です。",
   features:["FM"]},
  {id:"tfd", ext:".tfd", name:"TurboFM Dump", aka:"TFD", cat:"fm", chip:"YM2203 ×2 (TurboFM)", platform:"ZX Spectrum (TurboFM 拡張)", exts:[".tfd"], plugins:["TFD"],
   desc:"TurboFM のレジスタダンプ。",
   long:"ZXTune の TFD プラグインで再生します。",
   features:["FM","レジスタダンプ"]},
  {id:"tfm", ext:".tfe", name:"TFM Music Maker", aka:"TFE / TF0", cat:"fm", chip:"YM2203 ×2 (TurboFM)", platform:"ZX Spectrum (TurboFM 拡張)", exts:[".tfe",".tf0"], plugins:["TFE","TF0"],
   desc:"TurboFM 用トラッカー TFM Music Maker のモジュール。",
   long:"v1.3 以降の曲 (.tfe) と v0.1〜1.2 の曲 (.tf0) を、それぞれ別のプラグインで再生します。",
   features:["FM"]},
  {id:"etracker", ext:".cop", name:"E-Tracker v1.x", aka:"COP", cat:"fm", chip:"SAA1099", platform:"SAM Coupé", exts:[".cop"], plugins:["COP"],
   desc:"SAM Coupé の SAA1099 用トラッカー E-Tracker のモジュール。",
   long:"SAA1099 は6チャンネルの音源チップです。エンジンでの ID は COP です。",
   features:["SAA1099 6ch"]},

  // Consoles and computers, played by emulating their sound hardware
  {id:"spc", ext:".spc", name:"SNES SPC700", aka:"SPC", cat:"console", chip:"SPC700 + S-DSP", platform:"スーパーファミコン / SNES", exts:[".spc"], plugins:["SPC"],
   desc:"スーパーファミコンの音源部 (SPC700 と S-DSP) の状態を丸ごと保存したダンプ。",
   long:"S-DSP の BRR サンプルやエコーも含めて再生します。",
   features:["エミュレーション"]},
  {id:"nsf", ext:".nsf", name:"NES Sound Format", aka:"NSF", cat:"console", chip:"RP2A03 (+ 拡張音源)", platform:"ファミコン / NES", exts:[".nsf"], plugins:["NSF"],
   desc:"ファミコンのサウンドドライバと音楽データを収めた形式。",
   long:"6502 のコードを実行して鳴らします (Game_Music_Emu)。複数の曲は1曲ずつプレイリストに展開されます。",
   features:["エミュレーション","複数曲を展開"]},
  {id:"nsfe", ext:".nsfe", name:"Extended NSF", aka:"NSFe", cat:"console", chip:"RP2A03 (+ 拡張音源)", platform:"ファミコン / NES", exts:[".nsfe"], plugins:["NSFE"],
   desc:"NSF に曲名や曲の長さなどの情報を加えた拡張形式。",
   long:"Game_Music_Emu で再生し、複数の曲は1曲ずつプレイリストに展開されます。",
   features:["エミュレーション","複数曲を展開"]},
  {id:"gbs", ext:".gbs", name:"GameBoy Sound", aka:"GBS", cat:"console", chip:"LR35902", platform:"ゲームボーイ", exts:[".gbs"], plugins:["GBS"],
   desc:"ゲームボーイの音楽を収めた形式。",
   long:"4チャンネルの内蔵音源を Game_Music_Emu でエミュレートし、複数の曲は1曲ずつ展開されます。",
   features:["エミュレーション","複数曲を展開"]},
  {id:"hes", ext:".hes", name:"Home Entertainment System", aka:"HES", cat:"console", chip:"HuC6280", platform:"PC エンジン", exts:[".hes"], plugins:["HES"],
   desc:"PC エンジンの音楽を収めた形式。",
   long:"HuC6280 の6チャンネル波形メモリ音源を Game_Music_Emu でエミュレートし、複数の曲は1曲ずつ展開されます。",
   features:["エミュレーション","複数曲を展開"]},
  {id:"sid", ext:".sid", name:"Commodore 64 SID", aka:"PSID / RSID", cat:"console", chip:"MOS 6581 / 8580", platform:"Commodore 64", exts:[".sid"], plugins:["SID"],
   desc:"C64 の音源チップ SID の音楽 (PSID / RSID)。",
   long:"3ボイスとフィルタを持つ SID を libsidplayfp でエミュレートします。HVSC に収められた曲もそのまま再生でき、複数の曲は1曲ずつ展開されます。",
   features:["エミュレーション","複数曲を展開"]},
  {id:"sap", ext:".sap", name:"Slight Atari Player", aka:"SAP", cat:"console", chip:"POKEY", platform:"Atari 8bit", exts:[".sap",".rmt"], plugins:["SAP","RMT"],
   desc:"Atari 8bit (POKEY) の音楽形式。",
   long:"ASAP で再生します。Raster Music Tracker (RMT) のモジュールにも対応し、複数の曲は1曲ずつ展開されます。",
   features:["エミュレーション","RMT 対応"]},
  {id:"kss", ext:".kss", name:"KSS / KSSX", aka:"KSS", cat:"console", chip:"Z80 + PSG / SCC / FM など", platform:"MSX など", exts:[".kss",".kssx"], plugins:["KSS","KSSX"],
   desc:"MSX などの Z80 機の音楽を収めた形式。",
   long:"Game_Music_Emu で再生し、KSSX の複数曲は1曲ずつ展開されます。",
   features:["エミュレーション"]},
  {id:"psf", ext:".psf", name:"PSF ファミリー", aka:"PSF", cat:"console", chip:"各機種の音源", platform:"PS1 / PS2 / サターン / ドリームキャスト / N64 / GBA / DS", exts:[".psf",".psf2",".ssf",".dsf",".usf",".gsf",".2sf",".ncsf"], plugins:["PSF","PSF2","SSF","DSF","USF","GSF","2SF","NCSF"],
   desc:"ゲーム機の音楽プログラムとデータを収めた PSF 系の形式。",
   long:"PSF (PS1)、PSF2 (PS2)、SSF (サターン)、DSF (ドリームキャスト)、USF (N64)、GSF (GBA)、2SF と NCSF (DS) を扱います。ライブラリファイルと組で1曲になる mini 形式 (.minipsf など) は、Web プレイヤーがライブラリを読み込めないため、まだ再生できません。",
   features:["エミュレーション"]},
  {id:"vgm", ext:".vgm", name:"Video Game Music", aka:"VGM", cat:"console", chip:"多数の音源チップ", platform:"メガドライブ、マスターシステムなど", exts:[".vgm",".vgz"], plugins:["VGM"],
   desc:"音源チップへの書き込みを記録したログ形式。多くのチップに対応。",
   long:"libvgm で再生します。gzip 圧縮された .vgz も、中身を展開して再生します。VGMRips で多数の曲が公開されています。",
   features:["レジスタログ","多チップ"]},
  {id:"gym", ext:".gym", name:"Genesis YM2612", aka:"GYM", cat:"console", chip:"YM2612 + SN76489", platform:"メガドライブ / Genesis", exts:[".gym"], plugins:["GYM"],
   desc:"メガドライブの音源への書き込みを記録したログ形式。",
   long:"Game_Music_Emu で再生します (エンジンでの説明は Genesis YM2612 (unpacked))。",
   features:["レジスタログ"]},
  {id:"s98", ext:".s98", name:"Sound 98", aka:"S98", cat:"console", chip:"FM 音源など", platform:"PC-98 など", exts:[".s98"], plugins:["S98"],
   desc:"PC-98 などの音源チップへの書き込みを記録したログ形式。",
   long:"ZXTune の S98 プラグインで再生します。",
   features:["レジスタログ"]},

  // Packers: unpacked first, then searched for music
  {id:"hrust", ext:"—", name:"Hrust", aka:"HRUST", cat:"packed", chip:"—", platform:"ZX Spectrum", exts:[], plugins:["HRUST1","HRUST2","HRUST23","HRIP"],
   desc:"ZX Spectrum の圧縮ツール Hrust (v1.x / 2.1 / 2.3) で圧縮されたデータ。",
   long:"決まった拡張子はなく、ZXTune は中身を見て判定し、展開してから曲を探します。Hrust の書庫 Hrip (.hrp) も開けます。",
   features:["自動展開"]},
  {id:"hrum", ext:".hrm", name:"Hrum v3.x", aka:"HRUM", cat:"packed", chip:"—", platform:"ZX Spectrum", exts:[".hrm"], plugins:["HRUM"],
   desc:"Hrum 3.x で圧縮されたデータ。",
   long:"展開してから中の曲を探します。",
   features:["自動展開"]},
  {id:"cc3", ext:".cc3", name:"CodeCruncher v3.x", aka:"CC3", cat:"packed", chip:"—", platform:"ZX Spectrum", exts:[".cc3"], plugins:["CC3"],
   desc:"CodeCruncher 3.x で圧縮されたデータ。",
   long:"展開してから中の曲を探します。名前の似た CompressorCode v4 (CC4) は別のプラグインです。",
   features:["自動展開"]},
  {id:"megalz", ext:"—", name:"MegaLZ", aka:"MEGALZ", cat:"packed", chip:"—", platform:"ZX Spectrum", exts:[], plugins:["MEGALZ"],
   desc:"MegaLZ で圧縮されたデータ。",
   long:"決まった拡張子はなく、中身を見て判定し、展開してから曲を探します。",
   features:["自動展開"]},
  {id:"lzs", ext:".lzs", name:"ASC LZS Pack", aka:"LZS", cat:"packed", chip:"—", platform:"ZX Spectrum", exts:[".lzs"], plugins:["LZS"],
   desc:"ASC LZS Pack で圧縮されたデータ。",
   long:"展開してから中の曲を探します。",
   features:["自動展開"]},
  {id:"trush", ext:".trs", name:"Trush Compressor v3.x", aka:"TRUSH", cat:"packed", chip:"—", platform:"ZX Spectrum", exts:[".trs"], plugins:["TRUSH"],
   desc:"Trush Compressor 3.x で圧縮されたデータ。",
   long:"展開してから中の曲を探します。",
   features:["自動展開"]},
  {id:"dsq", ext:".dsq", name:"DataSqueezer v4.x", aka:"DSQ", cat:"packed", chip:"—", platform:"ZX Spectrum", exts:[".dsq"], plugins:["DSQ"],
   desc:"DataSqueezer 4.x で圧縮されたデータ。",
   long:"展開してから中の曲を探します。",
   features:["自動展開"]},

  // Archives, disk images, snapshots
  {id:"trd", ext:".trd", name:"TRD (TR-DOS ディスクイメージ)", aka:"TRD", cat:"archived", chip:"—", platform:"ZX Spectrum", exts:[".trd"], plugins:["TRD"],
   desc:"TR-DOS のフロッピーディスクをそのまま写したイメージ (80トラック両面で 640KB)。",
   long:"ディスク上のファイルを1つずつ調べ、見つかった曲をプレイリストに展開します。",
   features:["ディスクイメージ","複数曲を展開"]},
  {id:"scl", ext:".scl", name:"SCL", aka:"SCL", cat:"archived", chip:"—", platform:"ZX Spectrum", exts:[".scl"], plugins:["SCL"],
   desc:"TR-DOS のファイルだけをまとめた形式。空き領域を持たないので TRD より小さくなります。",
   long:"中のファイルを1つずつ調べ、見つかった曲をプレイリストに展開します。",
   features:["ディスクイメージ","複数曲を展開"]},
  {id:"fdi", ext:".fdi", name:"FDI / TD0 / DSK", aka:"FDI", cat:"archived", chip:"—", platform:"ZX Spectrum など", exts:[".fdi",".td0",".dsk"], plugins:["FDI","TD0","DSK"],
   desc:"Full Disk Image、TeleDisk、DSK のフロッピーディスクイメージ。",
   long:"ディスク上のファイルを調べ、見つかった曲をプレイリストに展開します。",
   features:["ディスクイメージ"]},
  {id:"zip", ext:".zip", name:"ZIP / RAR / 7z / LHA / GZip", aka:"ZIP", cat:"archived", chip:"—", platform:"汎用", exts:[".zip",".rar",".7z",".lha",".lzh",".gz"], plugins:["ZIP","RAR","7ZIP","LHA","GZIP"],
   desc:"一般的な圧縮書庫。中の曲をそのまま再生します。",
   long:"書庫の中の書庫やディスクイメージも、たどって調べます。",
   features:["書庫","入れ子も展開"]},
  {id:"zxzip", ext:".zip", name:"ZXZip", aka:"ZXZIP", cat:"archived", chip:"—", platform:"ZX Spectrum", exts:[".zip"], plugins:["ZXZIP"],
   desc:"ZX Spectrum の書庫 ZXZip。",
   long:"PC の ZIP とは中身が異なり、別のプラグインが扱います (ZX 側でも .zip という名前が使われます)。",
   features:["書庫"]},
  {id:"hobeta", ext:".$c", name:"Hobeta", aka:"HOBETA", cat:"archived", chip:"—", platform:"ZX Spectrum", exts:[".$b",".$c",".$m"], plugins:["HOBETA"],
   desc:"TR-DOS のファイル1つにヘッダを付けて保存する形式。",
   long:"拡張子の2文字目は元のファイルの種類 (B, C, M など) です。",
   features:["ファイル単体"]},
  {id:"z80", ext:".z80", name:"スナップショット (Z80 / SNA / SZX)", aka:"Z80", cat:"archived", chip:"—", platform:"ZX Spectrum", exts:[".z80",".sna",".szx"], plugins:["Z80V145","Z80V20","Z80V30","SNA128","ZXSTATE"],
   desc:"ZX Spectrum エミュレータが保存したメモリの状態。",
   long:"ZXTune はメモリの中から曲のデータを探します。Z80 (v1.45 / 2.x / 3.x)、SNA 128k、SZX に対応します。",
   features:["スナップショット"]},

  // Streams and sample modules
  {id:"mp3", ext:".mp3", name:"MP3 / OGG / FLAC / WAV", aka:"MP3", cat:"audio", chip:"—", platform:"汎用", exts:[".mp3",".ogg",".flac",".wav"], plugins:["MP3","OGG","FLAC","WAV"],
   desc:"一般的な音声ファイル。",
   long:"ほかに vgmstream により、ADX、HCA、FSB などゲームで使われる多数の音声形式も再生できます (全プラグイン一覧を参照)。",
   features:["音声ストリーム"]},
  {id:"mod", ext:".mod", name:"MOD / XM / S3M / IT ほか", aka:"MOD", cat:"audio", chip:"サンプル", platform:"Amiga / PC", exts:[".mod",".xm",".s3m",".it",".669",".mtm",".med"], plugins:["MOD","XM","S3M","IT","669","MTM","MED"],
   desc:"サンプルを使うトラッカーのモジュール。",
   long:"libopenmpt と libxmp で、Amiga の MOD から FastTracker II (XM)、ScreamTracker 3 (S3M)、Impulse Tracker (IT) まで数十種を再生します。Unreal の UMX に入ったモジュールも開けます。",
   features:["サンプルモジュール"]},
];

window.FORMAT_CATS = [
  {id:"aym", label:"AY/YM", icon:"🎹", color:"#00FFD1", desc:"AY-3-8910 / YM2149 の曲。PT3, STC, ASC, SQT, YM, VTX, AY, TurboSound など。"},
  {id:"digital", label:"デジタル / 合成", icon:"🥁", color:"#FFD60A", desc:"ZX Spectrum のサンプルトラッカー (DST, DMM, PDT など) と、Amiga の AHX、Farbrausch V2 などのソフトウェア合成。"},
  {id:"fm", label:"FM / SAA", icon:"🎛️", color:"#FF3B82", desc:"TurboFM (YM2203×2) 用の TFC / TFD / TFM Music Maker と、SAA1099 の E-Tracker。"},
  {id:"console", label:"ゲーム機 / パソコン", icon:"🎮", color:"#7C5CFF", desc:"音源をエミュレートして再生する形式。SPC, NSF, GBS, HES, SID, SAP, KSS, PSF, VGM など。"},
  {id:"packed", label:"圧縮", icon:"📦", color:"#00E5FF", desc:"ZX Spectrum の圧縮形式。Hrust, Hrum, CodeCruncher, MegaLZ, LZS, Trush などを展開して中の曲を探します。"},
  {id:"archived", label:"書庫 / ディスク / スナップショット", icon:"💾", color:"#FF8A00", desc:"ZIP, RAR, 7z, TRD, SCL, FDI, Hobeta, Z80 スナップショットなど。中を調べて曲を展開します。"},
  {id:"audio", label:"音声 / モジュール", icon:"🎧", color:"#00FF88", desc:"MP3, OGG, FLAC, WAV とゲームの音声形式 (vgmstream)、MOD / XM / S3M / IT など (libopenmpt, libxmp)。"},
];
